# Dev environment overrides
spring:
  config:
    activate:
      on-profile: dev

easyshop:
  services:
    auth: ${DEV_AUTH_SERVICE_URL}
    product: ${DEV_PRODUCT_SERVICE_URL}
    purchase: ${DEV_PURCHASE_SERVICE_URL}
  auth:
    issuer-uri: ${DEV_AUTH_ISSUER_URI}
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
