# Production environment overrides
spring:
  config:
    activate:
      on-profile: prod

easyshop:
  services:
    auth: ${PROD_AUTH_SERVICE_URL}
    product: ${PROD_PRODUCT_SERVICE_URL}
    purchase: ${PROD_PURCHASE_SERVICE_URL}
  auth:
    issuer-uri: ${PROD_AUTH_ISSUER_URI}
    # Email verification security (Production-grade)
    verification-code-length: 8
    verification-ttl-minutes: 10
    verification-max-attempts: 3
    verification-resend-cooldown-seconds: 120
    verification-ip-rate-limit-enabled: true
    verification-ip-max-attempts: 10
    verification-ip-window-minutes: 60
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
  mail:
    from-email: ${MAIL_FROM_EMAIL:noreply@easyshop.com}
    from-name: ${MAIL_FROM_NAME:EasyShop}
