# Production overrides
spring:
  config:
    activate:
      on-profile: prod

easyshop:
  services:
    auth: ${PROD_AUTH_SERVICE_URL:https://auth.easyshop.com}
    product: ${PROD_PRODUCT_SERVICE_URL:https://product.easyshop.com}
    purchase: ${PROD_PURCHASE_SERVICE_URL:https://purchase.easyshop.com}
  auth:
    issuer-uri: ${PROD_AUTH_ISSUER_URI:${easyshop.services.auth}}
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST:prod-postgres}:${PROD_DB_PORT:5432}/${PROD_DB_NAME:easyshop}
    username: ${PROD_DB_USER:easyshop}
    password: ${PROD_DB_PASSWORD:change-me}
