# Dev environment overrides
spring:
  config:
    activate:
      on-profile: dev

easyshop:
  services:
    auth: ${DEV_AUTH_SERVICE_URL}
    product: ${DEV_PRODUCT_SERVICE_URL}
    purchase: ${DEV_PURCHASE_SERVICE_URL}
  auth:
    issuer-uri: ${DEV_AUTH_ISSUER_URI}
    # Email verification security (Production-grade)
    verification-code-length: 6
    verification-ttl-minutes: 10
    verification-max-attempts: 3
    verification-resend-cooldown-seconds: 120
    verification-ip-rate-limit-enabled: true
    verification-ip-max-attempts: 10
    verification-ip-window-minutes: 60
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
  mail:
    from-email: ${MAIL_FROM_EMAIL:noreply-dev@easyshop.com}
    from-name: ${MAIL_FROM_NAME:EasyShop DEV}
