# Production environment overrides
spring:
  config:
    activate:
      on-profile: prod

easyshop:
  services:
    auth: ${PROD_AUTH_SERVICE_URL}
    product: ${PROD_PRODUCT_SERVICE_URL}
    purchase: ${PROD_PURCHASE_SERVICE_URL}
  auth:
    issuer-uri: ${PROD_AUTH_ISSUER_URI}
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
