server:
  port: 9001

spring:
  datasource:
    url: ${easyshop.datasource.url}
    username: ${easyshop.datasource.username}
    password: ${easyshop.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${auth.datasource.schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${auth.datasource.schema}
    default-schema: ${auth.datasource.schema}
    baseline-on-migrate: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      authorizationserver:
        issuer: ${easyshop.auth.issuer-uri}

auth:
  datasource:
    schema: ${AUTH_DB_SCHEMA}

WEBAPP_REDIRECT_URI: ${WEBAPP_REDIRECT_URI}
WEBAPP_POST_LOGOUT_REDIRECT_URI: ${WEBAPP_POST_LOGOUT_REDIRECT_URI}
GATEWAY_CLIENT_SECRET: ${GATEWAY_CLIENT_SECRET}
PRODUCT_SERVICE_CLIENT_SECRET: ${PRODUCT_SERVICE_CLIENT_SECRET}
PURCHASE_SERVICE_CLIENT_SECRET: ${PURCHASE_SERVICE_CLIENT_SECRET}
