server:
  port: 9002

spring:
  datasource:
    url: ${easyshop.datasource.url}
    username: ${easyshop.datasource.username}
    password: ${easyshop.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${product.datasource.schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${product.datasource.schema}
    default-schema: ${product.datasource.schema}
    baseline-on-migrate: true
  sql:
    init:
      mode: never

product:
  datasource:
    schema: ${PRODUCT_DB_SCHEMA}
