server:
  port: 9003

spring:
  datasource:
    url: ${easyshop.datasource.url}
    username: ${easyshop.datasource.username}
    password: ${easyshop.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${purchase.datasource.schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${purchase.datasource.schema}
    default-schema: ${purchase.datasource.schema}
    baseline-on-migrate: true
  sql:
    init:
      mode: never

purchase:
  datasource:
    schema: ${PURCHASE_DB_SCHEMA}

product:
  service:
    url: ${PRODUCT_SERVICE_INTERNAL_URL}
